Squashed commit of the following:
commit 0204c25ef5d6c9ecffe511eb3135d681695c5e55
Merge: aa53e0b3 807b88dc
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jul 14 11:49:02 2025 -0400

    ci: move macOS `azure-pipelines.yml` to GitHub Actions with a matrix (#1275)

    * Fixes #1278.

commit aa53e0b3dee6e46bb7b88206e2a31969d2a0620f
Merge: effa6750 58a111a1
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jul 14 11:46:27 2025 -0400

    ci: switch python to use `uv` (#1276)

    This simplifies a lot of things (especially once we add macOS in GitHub
    Actions in #1275) and is faster, too. `uv` is great!

commit 807b88dc74233328eecc72a476f2562b1d19c915
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jul 14 03:51:45 2025 -0400

    ci: move macOS `azure-pipelines.yml` to GitHub Actions with a matrix

commit 58a111a10ffbb12c1ef7b377e63b6f10b1ce4a4a
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jul 14 04:04:20 2025 -0400

    ci: switch python to use `uv`

commit effa6750ee946518bbf7d78878ef9d0a5c218e8b
Merge: 17d24e30 3aca2525
Author: Khyber Sen <kkysen@gmail.com>
Date:   Sat Jul 12 00:25:32 2025 -0400

    fix compilation error on clang/llvm 21 (#1274)

    GCCAsmStmt::getOutputConstraint() now return `std::string` instead of
    `StringRef`. this change is introduced in
    https://github.com/llvm/llvm-project/pull/131003

commit 3aca25250daae57faa3dd2e04f4e002e87763811
Author: bungcip <bungcip@gmail.com>
Date:   Sat Jul 12 09:57:36 2025 +0700

    fix compilation error on clang/llvm 21

    GCCAsmStmt::getOutputConstraint() now return `std::string` instead of `StringRef`. this change is introduced in https://github.com/llvm/llvm-project/pull/131003

commit 17d24e30ba701b718d3f47213e4d93013e73e366
Author: fw <fw@immunant.com>
Date:   Fri Jul 11 00:33:38 2025 -0400

    transpile: operators: resolve type when checking for unsignedness

    other code in operators.rs remembers to do this, but this method forgot

    fixes #1024

commit 0153f8fe253ca7107ace2ebe53d38aea8093d5b3
Author: fw <fw@immunant.com>
Date:   Fri Jul 11 09:12:11 2025 -0400

    transpile: snapshots: add snapshot for #1024

    this isn't how we want this code to be transpiled (it should use `wrapping_mul`), but it is how it transpiles now

commit c6cf1fdeafa8d1941c7c501877a2496e9393853b
Author: fw <fw@immunant.com>
Date:   Thu Jul 10 12:53:54 2025 -0400

    transpile: snapshots: add dummy files so insta::glob sees multiple tests

    insta handily uses different snapshot file naming schemes dependent on whether a glob finds one or multiple files. as we only have one platform-dependent test yet, it doesn't include the @filename suffix, but it will when we add more.

    for now, add a dummy test so that insta always uses the `@file.c` suffix; we should delete the dummy test when we have more platform-specific tests.

commit e6c83d3bef23e264be90e95457c900502d77817c
Author: fw <fw@immunant.com>
Date:   Thu Jul 10 12:18:27 2025 -0400

    transpile: snapshot: allow platform-dependent snapshots

    we need to support different output on different platforms due to various
    differences that we can't paper over. for example, macOS defines some builtins
    with different types than Linux, and macOS libc and glibc have different typedef
    setups for fixed-size types, resulting in different type alias preambles.

    support these by appending the operating system to the snapshot name for
    results that may vary by platform.

commit da66496a03eb5d1cd17bb52519081595206e3022
Author: fw <fw@immunant.com>
Date:   Thu Jul 10 12:04:14 2025 -0400

    transpile: snapshot: build to stdout rather than creating+deleting rlib

commit a8e664add48f0162b70b80d48cc337234a4f3348
Author: fw <fw@immunant.com>
Date:   Thu Jul 10 22:36:31 2025 -0400

    ci: allow reusing testsuite workflow

commit b2ba4bf6d3eda778884c7620faeb888dfcd23c94
Merge: 95c05a37 67714280
Author: Khyber Sen <kkysen@gmail.com>
Date:   Wed Jul 9 18:32:04 2025 -0400

    Add `tests/requirements.txt` dependencies into nix python environment (#1269)

    The nix development environment was missing some python packages, which
    meant it couldn't run some of the test scripts, e.g.:

    ```
    ./scripts/test_translator.py -d tests
    ```

    This makes sure the necessary libraries from `tests/requirements.txt`
    are included. There may be better ways to do this (e.g., using something
    like https://github.com/nix-community/pip2nix to generate this
    automatically), but I'm not too familiar with the python ecosystem, and
    this seemed like a simpler solution for now.

    Thanks!

commit 95c05a3744baad9be8b178bcb07c598a5a03d2d2
Merge: 8aa8d0d0 18ef2c14
Author: Khyber Sen <kkysen@gmail.com>
Date:   Wed Jul 9 16:40:32 2025 -0400

    `transpile`: emit `.rotate_{left,right}` instead of `core::intrinsics::rotate_{left,right}` (#1260)

    * Fixes #1256.

    These methods are stable (no `core::intrinsics` needed), which is
    greatly preferred. Also, being stable means their signatures won't
    change like the intrinsics have.

    cc @folkertdev.

commit 8aa8d0d02151dd7f80f36f7d04933889149639e2
Merge: 7d27e484 1e3e5dcb
Author: Khyber Sen <kkysen@gmail.com>
Date:   Wed Jul 9 16:16:54 2025 -0400

    `transpile`: impl `__builtin_rotateright*` as `core::intrinsics::rotate_right` (#1259)

    * Fixes #1251.

commit 7d27e484350981178c4f4f5fd5e3acc7c564b151
Merge: dd96fada 5087f24b
Author: Khyber Sen <kkysen@gmail.com>
Date:   Wed Jul 9 16:16:26 2025 -0400

    transpile: fix doc tests on aarch64 (`c_char` is unsigned there) (#1255)

    While reviewing some other PRs, I noticed doc tests fail on aarch64
    since `c_char` is unsigned there.

commit 67714280d4d3be62dedfc1aaf6480f24b2befd21
Author: Calvin Beck <hobbes@ualberta.ca>
Date:   Wed Jul 9 14:59:03 2025 -0400

    Add tests/requirements.txt dependencies into nix python environment.

commit dd96fadaf3acfd76d2d08f560d589a9de2298264
Author: Christiaan Biesterbosch <Kriskras99@users.noreply.github.com>
Date:   Thu Oct 24 00:23:03 2024 +0200

    Add test for __builtin_ia32_vperm2f128_pd256/_mm256_permute2f128_pd

commit afef74efa5db4bcfe4efba45919131e0dd7396e1
Author: Christiaan Biesterbosch <Kriskras99@users.noreply.github.com>
Date:   Wed Sep 18 16:03:10 2024 +0200

    Add SIMD intrinsic __builtin_ia32_vperm2f128_pd256/_mm256_permute2f128_pd

commit ef010b5bdbe3dbcfc486395dc3daf928249caa1d
Author: fw <fw@immunant.com>
Date:   Tue Jul 8 19:14:41 2025 -0400

    transpile: operators: improve docs

commit 7d03fd18a9b1aa1d988c00f455eb277abc1cb73d
Author: fw <fw@immunant.com>
Date:   Tue Jul 8 19:10:45 2025 -0400

    transpile: correct old comment typo

commit 3211303fe2c8bd2d80fa85095cf3609d264f1ae5
Author: fw <fw@immunant.com>
Date:   Tue Jul 8 19:10:11 2025 -0400

    transpile: conversion: don't expose TypedAstContext publicly

    the ConversionContext only needs to expose it once it's been fully built

commit 1bf884002896e5285dc42d89984d22d9d21fe573
Author: fw <fw@immunant.com>
Date:   Tue Jul 8 10:34:11 2025 -0400

    transpile: include path in error message

commit e56acbcebdf759a4bcf0fc7c6390d5b0ea0de91b
Author: fw <fw@immunant.com>
Date:   Sat Jul 5 02:34:49 2025 -0400

    transpile: rename compute_size_of_ty -> mk_size_of_ty_expr

    this function just constructs an expression, and is confusingly named very similarly to compute_size_of_type

commit 5b0f63f08f008b671a14d57fbf314238699ce863
Author: fw <fw@immunant.com>
Date:   Sat Jul 5 03:05:48 2025 -0400

    tweak clippy allow syntax

    'reason' isn't supported in our nightly but putting the reason on the same line as the allow makes the intent more obvious

commit 52fdd98cab1b44de0f778f6fa1258d784f3a0f90
Author: fw <fw@immunant.com>
Date:   Sat Jul 5 02:26:29 2025 -0400

    transpile: document ExprContext

commit bbb7ad1581ecd18ec80926b689d6af0c90331e30
Author: fw <fw@immunant.com>
Date:   Tue Jul 1 17:43:14 2025 -0400

    translate: fix old comment typo

commit 7e0770f2f7a98ac2e18d8bb8c0b98e3c365856a3
Author: fw <fw@immunant.com>
Date:   Fri Jun 27 12:54:58 2025 -0400

    ast-exporter: avoid magic number

commit f39e774c4a814a8ec365b5c783667630845014c2
Author: fw <fw@immunant.com>
Date:   Tue Jul 1 17:33:58 2025 -0400

    ast-exporter: use map_err

commit 2fed623aa2490ffbe46deb3a53d595a1b19938b8
Author: fw <fw@immunant.com>
Date:   Thu Jun 26 16:33:59 2025 -0400

    ast-exporter: cmake: allow compile-commands generation

    to facilitate development. also silence cmake version warning and change the C++ std to 17 as 14 does not support features like <optional>, which upsets clangd

commit 18ef2c14f8206b6980a07db9938f8e3d841b39a8
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 10:15:08 2025 -0700

    transpile: refactor out `fn convert_builtin_rotate`

commit 1e3e5dcb6dca63f42222bf7c0868024de3497cd2
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 09:54:18 2025 -0700

    transpile: impl `__builtin_rotateright*` as `core::intrinsics::rotate_right`

commit 4f032db5c23a6ccb135f7064e634ec27dc95e1f6
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 10:10:06 2025 -0700

    transpile: emit `.rotate_{left,right}` instead of `core::intrinsics::rotate_{left,right}`

    These methods are stable (no `core::intrinsics` needed), which is greatly preferred.
    Also, being stable means their signatures won't change like the intrinsics have.

commit cf6619f447b146e1f579674989c982a341e666e0
Author: Khyber Sen <kkysen@gmail.com>
Date:   Fri Jul 4 12:50:42 2025 -0700

    transpile: run all snapshot tests in a single glob

    This is needed so that `insta` removing the common prefix
    of all matches files in a single glob doesn't cause file names to clash.

commit c0e75867659c877b01b0f1935a2f285369bb6d0c
Author: Khyber Sen <kkysen@gmail.com>
Date:   Thu Jul 3 06:00:33 2025 -0700

    transpile: make `__builtin_rotateleft64` snapshot test `linux` only

    `__builtin_rotateleft64` has different signatures on linux vs. macos,
    using `unsigned long` on linux and `unsigned long long` on macos.
    This makes a single snapshot test not work, so this is made linux-only.
    More preferable would to only test it on macos,
    but this is more annoying to test locally (on linux) and generate the snapshot,
    as cross compiling with `c2rust transpile` is super straightforward.
    Also, hopefully we will soon use std primitive types
    and remove redundant casts, which should fix this.

commit 2db762bb38e9cd49610db6dc452529f056e036dd
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 09:50:05 2025 -0700

    transpile: add snapshot test for `__builtin_rotateleft`

commit be351db5499c526352ec16000fc2499a25100513
Merge: 67b47c30 5866da19
Author: Khyber Sen <kkysen@gmail.com>
Date:   Thu Jul 3 16:44:52 2025 -0400

    `transpile`: impl `__builtin_ia32_pause` and `__builtin_arm_yield` (#1263)

    * Part of #1245.

    Required to transpile modern curl (see
    https://github.com/curl/curl/issues/9058).

commit 5866da19c9655ca92eaebb4d619d015a45ee9a9d
Author: Khyber Sen <kkysen@gmail.com>
Date:   Thu Jul 3 05:27:02 2025 -0700

    transpile: impl `__builtin_arm_yield` as `core::hint::spin_loop`

    On `arm`, it's implemented as `yield`, although on `aarch64`,
    it's implemented as `isb` instead as this is more efficient.
    See <https://github.com/rust-lang/rust/commit/c064b6560b7ce0adeb9bbf5d7dcf12b1acb0c807>.
    `core::arch::aarch64::__yield()` could be used instead,
    but it's unstable (`#![feature(stdarch_arm_hints)]`), so it's not ideal.

commit f7a609393b9ab4d54feb851df06de414d30a7452
Author: Khyber Sen <kkysen@gmail.com>
Date:   Thu Jul 3 05:12:42 2025 -0700

    transpile: translate `__builtin_ia32_pause` as `core::hint::spin_loop` instead

    `spin_loop()` is implemented as `_mm_pause()` (the `pause` instruction) on `x86`/`x86_64`,
    but it's the safe and cross-platform version of it, so we prefer it.

    Furthermore, while the x86/x86_64 `_mm_pause` is stable now,
    the arm/aarch64 equivalent `__yield` is not and requires
    `#![feature(stdarch_arm_hints)]` (`aarch64`) and `#![feature(stdarch_arm_neon_intrinsics)]` (`arm`).
    `__builtin_ia32_pause` is obviously x86/x86_64 only, but I think it'd be better
    to support the more cross-platform version that makes
    implementing other architectures' equivalents a lot simpler.

commit 6277c65da9422901ade986021e51daef844afb07
Author: Khyber Sen <kkysen@gmail.com>
Date:   Thu Jul 3 05:05:04 2025 -0700

    transpile: don't group `__builtin_ia32_pause` w/ other SIMD functions as it's not SIMD

commit 67b47c3032b20c2e1fa47eda7df8ce5e55c9e5cc
Merge: 82acf86d cda6d160
Author: Khyber Sen <kkysen@gmail.com>
Date:   Thu Jul 3 07:39:44 2025 -0400

    Support C11 atomics required by dav1d (#814)

    * Fixes #293.
    * Supercedes #302.

    Useful documentation/context:

    - https://en.cppreference.com/w/c/atomic/atomic_compare_exchange.html
    - https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html
    -
    https://clang.llvm.org/docs/LanguageExtensions.html#c11-atomic-builtins

commit 51277f9d845bad2c00fde49966c2153f01a41ab5
Author: Khyber Sen <kkysen@gmail.com>
Date:   Thu Jul 3 04:39:11 2025 -0700

    transpile: add snapshot test for `__builtin_ia32_pause`

commit cda6d160920725a45c2dea7f7143443129af8e0e
Author: Khyber Sen <kkysen@gmail.com>
Date:   Thu Jul 3 03:56:36 2025 -0700

    transpile: remove TODO for `__c11_atomic_compare_exchange_strong` deref on `src` arg

commit 4dcdc970fdcb54e219f74d7a06ea1aa7b06253ff
Author: Per Larsen <perl@immunant.com>
Date:   Wed Jul 2 18:01:24 2025 -0700

    Support __builtin_ia32_pause

    Required by newer versions of curl.
    Docs: https://gcc.gnu.org/onlinedocs/gcc/x86-Built-in-Functions.html

commit 0f91a60969e232f9f73519344bd8e99a7493d505
Author: Khyber Sen <kkysen@gmail.com>
Date:   Wed Jul 2 01:21:11 2025 -0700

    transpile: add a C11 atomics snapshot test

commit 9e88e34f0019ba28e9acaf51920c974f34ee3226
Author: Khyber Sen <kkysen@gmail.com>
Date:   Wed Jul 2 01:05:31 2025 -0700

    transpile: some style nits from the C11 atomics impl

commit 8bee6dfa8e342a6f1d42acdec8036bed0108547e
Author: Per Larsen <perl@immunant.com>
Date:   Sun Feb 5 22:28:01 2023 -0800

    Handle some C11 atomic types and operations

    Add support for:
    __c11_atomic_compare_exchange_{strong,weak}
    __c11_atomic_exhange
    __c11_atomic_fetch_add
    __c11_atomic_fetch_and
    __c11_atomic_fetch_nand
    __c11_atomic_fetch_or
    __c11_atomic_fetch_sub
    __c11_atomic_init
    __c11_atomic_load
    __c11_atomic_store

    Variants of the above with explicit memory ordering are not supported.

commit 0169c24b473a70f510265e8235123d08e79310b2
Author: chrysn <chrysn@fsfe.org>
Date:   Thu Feb 2 19:45:37 2023 -0800

    c2rust-exporter: Remove Atomics warning

    As atomics are being implemented, these warnings are becoming wrong.
    Any operations on atomics that stay unimplmented will be caught more
    precisely at later translation stages.

commit fd6fc93ad61245c6d7cd34a681b86a49b2c22be7
Author: chrysn <chrysn@fsfe.org>
Date:   Wed Jun 8 13:26:19 2022 +0200

    C11 atomics: Add tag, move information over to Rust side

commit 82acf86dda1fc80e8292e1fa035937ff6403d526
Merge: f7ac1710 47014c56
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 14:09:01 2025 -0400

    `transpile`: some snapshot test fixes (#1258)

    cc @jameysharp

commit 47014c56a9f1fe3198bc2fd07c3ec2bd753e9320
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 09:52:26 2025 -0700

    transpile: compile C src in snapshot tests

commit ce6865803f06cc0492a566798fda6b73db694850
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 09:45:48 2025 -0700

    transpile: set `fail_on_error: true` for snapshot tests

commit 4d7fab719e349d80de39c18f4c11629ce010a1a4
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 09:45:32 2025 -0700

    transpile: set a more descriptive debug expr for snapshot tests

commit a50c49cc93fee7d609487a09014ea929b093e6b2
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 09:43:39 2025 -0700

    transpile: remove `*.rlib` artifacts from `rustc` on snapshot tests

commit e90e546ac6bc229c52b174706cd10988c49483a9
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 09:42:21 2025 -0700

    transpile: run `rustc` on snapshot tests

commit 10f5b5a6ff4ae9f0e215601c068a975a663d787a
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 09:40:37 2025 -0700

    transpile: check in snapshot test `*.rs` files

commit c9268132ddf52448eca2c56b4dc67b05c6802af0
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 09:36:15 2025 -0700

    transpile: refactor out test `fn transpile`

commit f7ac171051cabc8702bb7922723351926f5f14d5
Merge: 6df557bd 6c8d524a
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 02:47:41 2025 -0400

    Introduce some snapshot tests of c2rust-transpile (#1246)

    Here's a quick implementation of snapshot testing for c2rust-transpile.
    I'm open to bike-shedding, such as discussing how the test files are
    laid out, or any other requests. I thought I'd just put together a quick
    proof of concept to start discussion with.

commit 5087f24b6e7b30933ddd2f3a0a7026b61f0ddda4
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 02:20:36 2025 -0400

    transpile: fix doc tests on aarch64 (`c_char` is unsigned there)

commit 6c8d524a766a9bf03b9748080107c984ddbf7c1a
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 02:18:20 2025 -0400

    transpile: use more descriptive variable names in `tests/snapshots.rs`

commit e9b137e0e2832ce6b1eb74912289b1df63979a78
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 02:17:18 2025 -0400

    transpile: import items in `tests/snapshots.rs`

commit 57a81e0076ff6e1ca7abba7126f97069727a12f2
Author: Khyber Sen <kkysen@gmail.com>
Date:   Mon Jun 30 02:16:48 2025 -0400

    transpile: use a closure instead of `#[derive(Clone)]` on `TranspilerConfig`

commit f7b2b44aec23e9762040f35f0f089ba451f872c0
Author: Jamey Sharp <jamey@minilop.net>
Date:   Tue May 13 22:29:48 2025 -0700

    Introduce some snapshot tests of c2rust-transpile